name = "PCHIPInterpolation"
uuid = "afe20452-48d1-4729-9a8b-50fb251f06cd"
authors = ["Gabriel S. Gerlero"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
